router:
  ip: "192.168.1.1"
  password: "your_router_password"

urls:
  router_url: "http://192.168.1.1/login"
  submenu: "http://192.168.1.1/submenu"

xpaths:
  password_field: '//*[@id="password"]'
  download_button: '//*[@id="download"]'

settings:
  driver_path: "/path/to/geckodriver"
  timeout: 5
